* import pandas as pd -- To import Pandas library
* pd.read_csv - To import the CSV file in Jupyter notebook
* head() - It shows the first N rows in the data (by default, N=5)
* df.isnull( ).sum( ) - It detects the missing values from each column of the dataframe.
* df.drop(‘Col_name’ )   - To drop a column from dataframe.
* value_counts - In a column, it shows all the unique values with their count. It can be applied on a single column only.
* df.groupby(‘Col_1’)[‘Col_2’] .sum( ) - To create groups - Two Keys – Apply on Col_2 grouped by Col_1.
* df['Column_name'].map( { old1:new1 , old2:new2} ) – Change the all values of a column from old to new. We have to write for all values of column otherwise Nan will appear.
* df['Column_name'].mean() - To show Mean value of a column.
* df.groupby('Column_1').Column_2.describe() - To create groups based on Column1 and show statistics summary based on Column2.

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
import pandas as pd

In [5]:
data = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/data/Police Data.csv')

In [6]:
data

       stop_date stop_time  ...  stop_duration drugs_related_stop
0       1/2/2005      1:55  ...       0-15 Min              False
1      1/18/2005      8:15  ...       0-15 Min              False
2      1/23/2005     23:15  ...       0-15 Min              False
3      2/20/2005     17:15  ...      16-30 Min              False
4      3/14/2005     10:00  ...       0-15 Min              False
...          ...       ...  ...            ...                ...
65530  12/6/2012     17:54  ...       0-15 Min              False
65531  12/6/2012     22:22  ...       0-15 Min              False
65532  12/6/2012     23:20  ...       0-15 Min              False
65533  12/7/2012      0:23  ...            NaN              False
65534  12/7/2012      0:30  ...       0-15 Min              False

[65535 rows x 15 columns]

Warning: total number of rows (65535) exceeds max_rows (20000). Limiting to first (20000) rows.

## Instruction ( For Data Cleaning ) 
# **Q. 1)- Remove the column that only contains missing values.**

In [7]:
data.isnull().sum()

stop_date                 0
stop_time                 0
country_name          65535
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

In [11]:
data.drop(columns = 'country_name', inplace = True)

In [12]:
data

       stop_date stop_time  ... stop_duration  drugs_related_stop
0       1/2/2005      1:55  ...      0-15 Min               False
1      1/18/2005      8:15  ...      0-15 Min               False
2      1/23/2005     23:15  ...      0-15 Min               False
3      2/20/2005     17:15  ...     16-30 Min               False
4      3/14/2005     10:00  ...      0-15 Min               False
...          ...       ...  ...           ...                 ...
65530  12/6/2012     17:54  ...      0-15 Min               False
65531  12/6/2012     22:22  ...      0-15 Min               False
65532  12/6/2012     23:20  ...      0-15 Min               False
65533  12/7/2012      0:23  ...           NaN               False
65534  12/7/2012      0:30  ...      0-15 Min               False

[65535 rows x 14 columns]

##  Question ( Based on Filtering + Value Counts ) 
# **Q. 2) For Speeding , were Men or Women stopped more often ?**

In [14]:
data.head(2)

   stop_date stop_time  ... stop_duration  drugs_related_stop
0   1/2/2005      1:55  ...      0-15 Min               False
1  1/18/2005      8:15  ...      0-15 Min               False

[2 rows x 14 columns]

In [16]:
data[data.violation == 'Speeding'].driver_gender.value_counts()

M    25517
F    11686
Name: driver_gender, dtype: int64

## Question ( Groupby ) 
# **Q. 3) Does gender affect who gets searched during a stop ?**

In [17]:
data.head()

   stop_date stop_time  ... stop_duration  drugs_related_stop
0   1/2/2005      1:55  ...      0-15 Min               False
1  1/18/2005      8:15  ...      0-15 Min               False
2  1/23/2005     23:15  ...      0-15 Min               False
3  2/20/2005     17:15  ...     16-30 Min               False
4  3/14/2005     10:00  ...      0-15 Min               False

[5 rows x 14 columns]

In [21]:
data.groupby('driver_gender').search_conducted.sum()

driver_gender
F     366
M    2113
Name: search_conducted, dtype: int64

In [23]:
data.search_conducted.value_counts()

False    63056
True      2479
Name: search_conducted, dtype: int64

# Question ( mapping + data-type casting ) 
## **Q. 4) What is the mean stop_duration ?**

In [24]:
data.head()

   stop_date stop_time  ... stop_duration  drugs_related_stop
0   1/2/2005      1:55  ...      0-15 Min               False
1  1/18/2005      8:15  ...      0-15 Min               False
2  1/23/2005     23:15  ...      0-15 Min               False
3  2/20/2005     17:15  ...     16-30 Min               False
4  3/14/2005     10:00  ...      0-15 Min               False

[5 rows x 14 columns]

In [26]:
data['stop_duration'].value_counts()

0-15 Min     47379
16-30 Min    11448
30+ Min       2647
2                1
Name: stop_duration, dtype: int64

In [29]:
data['stop_duration'] = data['stop_duration'].map({'0-15 Min': 7.5, '16-30 Min': 24, '30+ Min ': 45})

In [30]:
data

       stop_date stop_time  ... stop_duration  drugs_related_stop
0       1/2/2005      1:55  ...           7.5               False
1      1/18/2005      8:15  ...           7.5               False
2      1/23/2005     23:15  ...           7.5               False
3      2/20/2005     17:15  ...          24.0               False
4      3/14/2005     10:00  ...           7.5               False
...          ...       ...  ...           ...                 ...
65530  12/6/2012     17:54  ...           7.5               False
65531  12/6/2012     22:22  ...           7.5               False
65532  12/6/2012     23:20  ...           7.5               False
65533  12/7/2012      0:23  ...           NaN               False
65534  12/7/2012      0:30  ...           7.5               False

[65535 rows x 14 columns]

In [32]:
data['stop_duration'].mean()

10.710974552501403

# Question ( Groupby , Describe )
## **Q. 5) Compare the age distributions for each violation.**

In [33]:
data.head()

   stop_date stop_time  ... stop_duration  drugs_related_stop
0   1/2/2005      1:55  ...           7.5               False
1  1/18/2005      8:15  ...           7.5               False
2  1/23/2005     23:15  ...           7.5               False
3  2/20/2005     17:15  ...          24.0               False
4  3/14/2005     10:00  ...           7.5               False

[5 rows x 14 columns]

In [34]:
data.groupby('violation').driver_age.describe()

                       count       mean        std  ...   50%   75%   max
violation                                           ...
Equipment             6507.0  31.682957  11.380671  ...  28.0  39.0  81.0
Moving violation     11876.0  36.736443  13.258350  ...  35.0  47.0  86.0
Other                 3477.0  40.362381  12.754423  ...  41.0  50.0  86.0
Registration/plates   2240.0  32.656696  11.150780  ...  30.0  40.0  74.0
Seat belt                3.0  30.333333  10.214369  ...  26.0  34.0  42.0
Speeding             37120.0  33.262581  12.615781  ...  30.0  42.0  88.0

[6 rows x 8 columns]